### ISSUE TITLE
Comparison to Vega-Lite

### ISSUE THREAD

**Issue by daslu** [dvdt/gyptis#5]
Thank you for this beautiful library!

It may be worth explaining, how this projects differs from [Vega-Lite](https://github.com/vega/vega-lite), which seems to have similar goals (on client side, though).

**Comment by dvdt** [comment]
Thanks for checking out gyptis!

Gyptis has two major components: 

1) The `gyptis.core` namespace provides functions for concisely generating the most common statistical graphics. You're correct that this namespace has very similar goals to vega-lite (and ggplot, and tableau, and myriad other plotting tools). When gyptis was being made, vega-lite was still in a very early phase of development. From what I remember, vega-lite did not support facetting until recently. Facetting is a huge part of my data vis workflow, and so I took it upon myself to build it into gyptis. 

2) Gyptis makes it easy to view rendered plots in the browser from the REPL. This is implemented in the `gyptis.view` namespace, and it enables you to e.g. fetch SQL query results => generate a vega spec using functions in `gyptis.core` (or even vega-lite!) => send to browser for viewing plots. The idea is to make it as frictionless as possible to go from a data table to viewing a plot.

These two components are designed to be decoupled. Ideally it would be straightforward to drop in vega-lite into this workflow. Currently, the only way to use vega-lite would be to compile the vega-lite spec into a vega spec, and then send the resulting vega spec to the browser. But, I'd be receptive to a feature request for `gyptis.view/plot!` to work with vega-lite specs directly (or something similar, like `gyptis.view/plot-vega-lite!`). Especially since it looks like vega-lite has progressed a lot in the past year.

**Comment by daslu** [comment]
Thanks for the detailed answer.

Yes, the second component you mentioned is actually very handy, in particular when working on a remote machine.

It has been quite easy to take other plots, generated by, e.g., [gorilla-plot](http://gorilla-repl.org/plotting.html), and (after some adaptation) plot them through gyptis.view/plot! . I will try to prepare a pull request as you suggested.
